name: futterapp
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Parse (Back4App) SDK
  parse_server_sdk_flutter: ^7.0.0

  # For environment variables (.env)
  flutter_dotenv: ^5.1.0

  # Use http version compatible with Parse SDK
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
